runs:
  using: composite
  steps:
    - name: Setup Selenium
      shell: bash
      run: |
        E2E_OUTPUT=base64
        PATH=$PATH:$HOME/webdrivers
        if [ ! -f $HOME/webdrivers/chromedriver ]; then wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip -P $HOME/webdrivers; unzip -d $HOME/webdrivers $HOME/webdrivers/chromedriver_linux64.zip; fi
